apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-build-and-deploy-pipeline
spec:
  params:
    - name: git-url
      description: The git repository URL to clone from
      default: 'https://github.com/psihovjeverica/ACE_Tekton_Operators.git'
      type: string
    - name: git-revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
      default: main
      type: string
    - name: bar-name-without-extension
      description: The name of the bar to be built, without the .bar extension
      default: mybarname
      type: string
    - name: bar-version
      description: The version of the bar to be built, without the .bar extension - will be appended to bar name
      default: '69'
      type: string
    - name: ace-toolkit-code-directory
      description: The base directory of the repository, containing ACE projects
      default: ace-toolkit-code
      type: string
    - name: server-license
      description: The license code for the deployed server. Default is set to ACE@CP4I production, needs to be updated appropriately. https://www.ibm.com/docs/en/app-connect/containers_cd?topic=resources-licensing-reference-app-connect-operator
      default: L-APEH-C49KZH
      type: string
    - name: server-usage
      description: The tag of the server. Default is set to ACE@CP4I production, needs to be updated appropriately. https://www.ibm.com/docs/en/app-connect/containers_cd?topic=resources-licensing-reference-app-connect-operator
      default: CloudPakForIntegrationProduction
      type: string
    - name: server-cpu-limit
      description: The CPU limit for ACE server
      default: 1000m
      type: string
    - name: server-memory-limit
      description: The RAM limit for ACE server
      default: 750Mi
      type: string
    - name: server-cpu-request
      description: The CPU request (minimum requirement for deployment) for ACE server
      default: 300m
      type: string
    - name: server-memory-request
      description: The RAM request (minimum requirement for deployment) for ACE server
      default: 350Mi
      type: string
    - name: default-app-name
      description: Name of default application which is created in case there are any resources which do not belong to library or app
      default: DEFAULT_APP_NAME
      type: string
    - name: integration-server-version
      description: The version of the ACE server to be deployed. Reference:https://www.ibm.com/docs/en/app-connect/containers_cd?topic=resources-specversion-values
      default: 12.0
      type: string
    - name: target-environment
      description: Target environment to be deployed, i.e. DEV/TEST/PROD. Depending on this value, different configuration will be applied, different license and server image, ...
      default: TEST
      type: string
    - name: integration-server-name
      description: The name of the integration server which will be deployed - will be used in Openshift deployment artefacts
      default: acedemotekton
      type: string
    - name: deployment-namespace
      description: The name of the Openshift namespace/project , where the integration server and configuration will be deployed
      default: ace-demo-tekton
      type: string
    - name: nexus-server-base-url
      description: The Base URL of the Nexus server where the bar file will be uploaded
      default: http://nexus-route-ace-demo-tekton.apps.ocp12.tec.cz.ibm.com
      type: string
    - name: nexus-repository-name
      description: The name of the Nexus repository, where the bar file will be uploaded
      default: ace-demo-tekton
      type: string
    - name: nexus-path
      description: The path of the Nexus repository, where the bar file will be uploaded, for example - "org/dept"
      default: org/test
      type: string
    - name: nexus-upload-user-name
      description: The Nexus user which will upload the bar file (default for Nexus is "admin")
      default: admin
      type: string
    - name: nexus-upload-user-password
      description: The Nexus user's password (default for Nexus is "admin123")
      default: admin123
      type: string
  tasks:
    - name: fetch-from-git
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: Task
        name: ace-git-clone
      workspaces:
        - name: output
          workspace: git-source
#        - name: ssh-directory
#          workspace: git-source
#        - name: ssl-ca-directory
#          workspace: git-source
#        - name: basic-auth
#          workspace: git-source
    - name: ace-build-bar
      params:
        - name: barNameWithoutExtension
          value: $(params.bar-name-without-extension)
        - name: barVersion
          value: $(params.bar-version)
        - name: aceToolkitCodeDirectory
          value: $(params.ace-toolkit-code-directory)
      runAfter:
        - fetch-from-git
      taskRef:
        kind: Task
        name: ace-build-bar
      workspaces:
        - name: output
          workspace: git-source
    - name: ace-generate-crs
      params:
        - name: targetEnvironment
          value: $(params.target-environment)
        - name: serverLicense
          value: $(params.server-license)
        - name: serverUsage
          value: $(params.server-usage)
        - name: serverCpuLimit
          value: $(params.server-cpu-limit)
        - name: serverMemoryLimit
          value: $(params.server-memory-limit)
        - name: serverCpuRequest
          value: $(params.server-cpu-request)
        - name: serverMemoryRequest
          value: $(params.server-memory-request)
        - name: defaultAppName
          value: $(params.default-app-name)
        - name: integrationServerVersion
          value: $(params.integration-server-version)
        - name: integrationServerName
          value: $(params.integration-server-name)
        - name: deploymentNamespace
          value: $(params.deployment-namespace)
        - name: nexusServerBaseURL
          value: $(params.nexus-server-base-url)
        - name: nexusRepositoryName
          value: $(params.nexus-repository-name)
        - name: nexusPath
          value: $(params.nexus-path)
        - name: barName
          value: $(params.bar-name-without-extension)
        - name: barVersion
          value: $(params.bar-version)
      runAfter:
        - fetch-from-git
      taskRef:
        kind: Task
        name: ace-generate-crs
      workspaces:
        - name: output
          workspace: git-source
    - name: ace-nexus-upload-bar
      params:
        - name: nexusServerBaseURL
          value: $(params.nexus-server-base-url)
        - name: nexusRepositoryName
          value: $(params.nexus-repository-name)
        - name: nexusPath
          value: $(params.nexus-path)
        - name: nexusUploadUserName
          value: $(params.nexus-upload-user-name)
        - name: nexusUploadUserPassword
          value: $(params.nexus-upload-user-password)
        - name: barNameWithoutExtension
          value: $(params.bar-name-without-extension)
        - name: barVersion
          value: $(params.bar-version)
      runAfter:
        - ace-build-bar
      taskRef:
        kind: Task
        name: ace-nexus-upload-bar
      workspaces:
        - name: output
          workspace: git-source
    - name: ace-deploy-crs
      params:
        - name: targetEnvironment
          value: $(params.target-environment)
      runAfter:
        - ace-generate-crs
        - ace-nexus-upload-bar
      taskRef:
        kind: Task
        name: ace-deploy-crs
      workspaces:
        - name: output
          workspace: git-source
  workspaces:
    - name: git-source
