apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: replace-with-server-name
  labels:
    labelname: sampleLabel
  namespace: replace-with-namespace
spec:
  annotations:
    key1: value1
    key2: value2
  enableMetrics: true
  license:
    accept: true
    license: replace-with-license
    use: replace-with-usage
  pod:
  #  volumes:
  #  - name: logs-splunk-volume
  #    persistentVolumeClaim:
  #      claimName: logs-splunk-claim
    containers:
  #    runtime:
  #      volumeMounts:
  #      - mountPath: /home/aceuser/generic
  #        name: logs-splunk-volume
        resources:
          limits:
            cpu: replace-with-cpu-limit
            memory: replace-with-memory-limit
          requests:
            cpu: replace-with-cpu-request
            memory: replace-with-memory-request
  adminServerSecure: true
  router:
    timeout: 120s
  defaultAppName: replace-with-default-app-name
  env:
    - name: ENV_VAR1
      value: SAMPLE_VALUE1
    - name: ENV_VAR2
      value: SAMPLE_VALUE2
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: replace-with-is-version
  logFormat: basic
  replicas: 1
  barURL: replace-With-Bar-URL
  configurations:
